#!/usr/bin/env zsh

transfer(){
  git rebase --onto master master link-vim-only
  git rebase --onto link-vim-only~1 link-nvim-only~1 link-nvim-only
}

reset(){
  git branch -f link-nvim-only origin/link-nvim-only
  git branch -f link-vim-only origin/link-vim-only
}

help(){
cat <<-EOF
  Usage: transfer-tree [COMMAND]
  Commands:
  t Transfer patch branches onto master
  r Reset patch branches to remotes
EOF
}

process(){
  case "$1" in
    "t")
      transfer;;
    "r")
      reset;;
    "help")
      help;;
    *)
      echo "Not a valid command"
      help;;
  esac
}

process "$@"
