#!/usr/bin/env bash

source "./lib/variables"

updateForOs() {
  printf "Updating programs\n"
  updateShared

  case "$(uname -s)" in
  Darwin)
    printf "Darwin based environment detected\n"
    updateMac
    ;;
  CYGWIN*)
    printf "Cygwin based environment detected\n"
    updateWindows
    ;;
  *)
    printf "No environment matched\n"
    ;;
  esac
}

updateShared() {
  sh "$HOME"/.oh-my-zsh/tools/upgrade.sh
  vim +PlugUpgrade +PlugUpdate +qa
}

updateWindows() {
  powershell -Command "Start-Process 'C:\\ProgramData\\chocolatey\\bin\\cup' 'all -y' -Verb runAs"
  powershell -Command "Start-Process 'C:\\Users\\Kevin Suen\\scoop\\shims\\scoop' 'update *'"
  powershell -Command "Start-Process 'C:\\tools\\cygwin\\cygwinsetup.exe' '--no-desktop --no-shortcuts --no-startmenu --quiet-mode'"
}

updateMac() {
  brew update
  brew upgrade
}

updateLocal() {
  local updateLocal="$target/.update.local"

  if [[ ! -f "$updateLocal" ]]; then
    return
  fi

  bash "$updateLocal"
}

help() {
  cat <<-EOF
Usage: update [COMMAND]
Commands:
all      Update shared and OS automatically update based on OS
shared   Update shared
windows  Update Windows
mac      Update Mac
local    Update local
EOF
}

process() {
  case "$1" in
  "all")
    updateForOs
    updateLocal
    ;;
  "shared")
    updateShared
    ;;
  "mac")
    updateMac
    ;;
  "windows")
    updateWindows
    ;;
  "local")
    updateLocal
    ;;
  "help")
    help
    ;;
  *)
    printf "Not a valid command\n\n"
    help
    ;;
  esac
}

process "$@"
