#!/usr/bin/env bash

karabiner_cli="/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli"
currentProfile=$("$karabiner_cli" --show-current-profile-name)

laptop="Laptop"
defaultProfile="Default Profile"
externalKeyboard="External Keyboard"

if [[ $currentProfile == "$laptop" ]]; then
  "$karabiner_cli" --select-profile "$defaultProfile"
elif [[ $currentProfile == "$defaultProfile" ]]; then
  "$karabiner_cli" --select-profile "$externalKeyboard"
elif [[ $currentProfile == "$externalKeyboard" ]]; then
  "$karabiner_cli" --select-profile "$laptop"
fi
