#!/bin/bash
setDefaults(){
  echo "Settings defaults"
  # Remove mouse acceleration
  defaults write .GlobalPreferences com.apple.mouse.scaling -1
  # Show full path in finder
  defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES
  # Remove hide/show animation
  defaults write com.apple.dock autohide-time-modifier -int 0 && killall Dock
  # Disable dashboard/widgets/F12
  defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock
  # Disable window animation
  defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
}

resetDefaults(){
  echo "Resets defaults"
  echo "TODO"
}

# Add Dock Spacer
addDockerSpacer(){
  defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'; killall Dock
}

help(){
  cat <<-EOF
  Usage: default [COMMAND]
  Commands:
  sd  Set default mac settings
  rd  Reset default mac settings set by 'sd'
  ads add spacer to docker
EOF
}

process(){
  case "$1" in
    sd)
      setDefaults;;
    ads)
      addDockerSpacer;;
    help)
      help;;
    -h)
      help;;
    *)
      help;;
  esac
}

process "$@"
