#!/usr/bin/env bash

# From: https://stackoverflow.com/a/28938235

export BGreen='\033[1;32m'
export BRed='\033[1;31m'
export BYellow='\033[1;33m'
export Bold='\033[1m'

export Green='\033[0;32m'
export Red='\033[0;31m'
export Yellow='\033[0;33m'

export Text_Reset='\033[0m'
