#!/usr/bin/env bash

# cd to the directory that script is being executed and set configs_dir to directory
configs_dir=$(
  cd "$(dirname "$0")" || exit
  pwd
)

export target=${TARGET:-"$configs_dir/.."}
