" Settings {
    set nocompatible                   " Use Vim settings, over Vi settings, has side effects must be set as early as possible
    set background=dark                " Color Theme
    set exrc                           " Allow project specific vimrc
    set secure                         " Disable unsafe commands in local .vimrc files
    set iminsert=0                     " Disable capslock"
    set backspace=2                    " Backspace deletes like most programs in insert mode
    set nobackup
    set nowritebackup
    set noswapfile                     " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
    set history=50
    set ruler                          " Show the cursor position all the time
    set showcmd                        " Display incomplete commands
    set incsearch                      " Do incremental searching
    set laststatus=2                   " Always display the status line
    set autowrite                      " Automatically :write before running commands
    set mouse=a                        " Enable mouse use in all modes
    set number                         " Show line numbers
    set showmode                       " Show the current mode
    set tabstop=2                      " Softtabs, 2 spaces
    set shiftwidth=2
    set shiftround
    set expandtab
    set nowrap
    set splitbelow                     " Pen new split panes to right and bottom, which feels more natural
    set splitright
    set nocursorcolumn                 " Speed up syntax highlighting
    set nocursorline
    syntax sync minlines=256
    set synmaxcol=150
    set re=1
    set incsearch                      " Shows the match while typing
    set hlsearch                       " Highlight found searches
    set ttyfast
    set timeoutlen=1000 ttimeoutlen=0
    set completeopt=menu
    set relativenumber
    set colorcolumn=80
" }

" Wildmenu settings {
    set wildmenu
    set wildmode=list:longest
    set wildmode=list:full
    set wildignore+=*.hg,*.git,*.svn                 " Version control
    set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
    set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " Binary images
    set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
    set wildignore+=*.spl                            " compiled spelling word lists
    set wildignore+=*.sw?                            " Vim swap files
    set wildignore+=*.DS_Store                       " OSX bullshit
    set wildignore+=*.luac                           " Lua byte code
    set wildignore+=migrations                       " Django migrations
    set wildignore+=go/pkg                           " Go static files
    set wildignore+=go/bin                           " Go bin files
    set wildignore+=go/bin-vagrant                   " Go bin-vagrant files
    set wildignore+=*.pyc                            " Python byte code
    set wildignore+=*.orig                           " Merge resolution files
" }

" File Type settings {
    au FileType make setlocal noexpandtab    " Hard code tabs in Makefiles
    au FileType markdown,gitcommit set spell " Spell checking

    au BufNewFile,BufRead *.vim setlocal noet ts=2 sw=2 sts=2
    au BufNewFile,BufRead *.txt setlocal noet ts=2 sw=2
    au BufNewFile,BufRead *.md setlocal noet ts=2 sw=2

    augroup filetypedetect
      au BufNewFile,BufRead *.swift setf swift
      au BufNewFile,BufRead .tmux.conf*,tmux.conf* setf tmux
      au BufNewFile,BufRead .nginx.conf*,nginx.conf* setf nginx
    augroup END
" }

" Misc {
    syntax on                            " Turn on syntax highlighting
    let mapleader = ","                  " Leader key to ','
    autocmd BufWritePost .vimrc source % " Autoreload vimrc on change
    autocmd FileType qf wincmd J         " Move quickfix window to the bottom

    " Prettify json
    com! JSONFormat %!python -m json.tool
" }

" Bindings {
    " Strip Trailing Whitespace & turn off hightlighting
    nnoremap <Leader>kw :%s/\s\+$//e<CR>:noh<CR>

    " Next error
    map <C-n> :cn<CR>
    " Previous error
    map <C-m> :cp<CR>

    " Remove search highlight
    nnoremap <leader><space> :nohlsearch<CR>

    " Tab between buffers
    nnoremap <leader>h :bprev<CR>
    nnoremap <leader>l :bnext<CR>
    nnoremap <leader>b :b

    " Redraw screen
    noremap <F5> :redraw!<CR>
" }

" Load plugins
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

" OS specific config
if filereadable(expand("~/.vimrc.oss"))
  source ~/.vimrc.oss
endif

" Local config
if filereadable(expand("/.vimrc.local"))
  source ~/.vimrc.local
endif

