# General {
    # Location of oh-my-zsh files
    export ZSH="$HOME/.oh-my-zsh"

    # Theme
    ZSH_THEME="robbyrussell"

    # Base16 Shell colors
    [[ -s "$HOME/.files/config/base16-eighties.dark.sh" ]] && source "$HOME/.files/config/base16-eighties.dark.sh"

    plugins=(git docker)

    # Initialize oh-my-zsh
    source "$ZSH"/oh-my-zsh.sh

    # Disable ctrl-s and ctrl-q http://unix.stackexchange.com/a/72092
    stty -ixon

    # Unalias git branch alias from git zsh git plugin
    unalias gb

    # Add relative bin to PATH
    export PATH=$PATH:./bin
    # Add relative node_modules/.bin to PATH
    export PATH=$PATH:./node_modules/.bin

    # Directory shortcuts
    prog (){ cd ~/Documents/Programming/$1; }
    compctl -W $HOME/Documents/programming/ -/ prog

    # Print Path in human readable format
    ppath (){
      echo -e ${PATH//:/\\n}
    }
# }

# Docker {
    if [[ $(docker-machine status default) != "Stopped" ]]; then
      # Docker machine default variables
      eval $(docker-machine env default)
    fi

    # Docker machine set env
    dm-set-env (){
      if [[ -z "$1" ]]; then
        eval "$(docker-machine env default)"
      fi
      if [[ -n "$1" ]]; then
        eval "$(docker-machine env "$1")"
      fi
    }
# }

# Emacs {
    # Allow emacs to use Shift + tab in term mode when showing completion list
    bindkey '^[[Z' reverse-menu-complete
# }

# OS specific settings
[[ -s "$HOME/.zshrc.oss" ]] && source "$HOME/.zshrc.oss"

# Local settings
[[ -s "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
